chat/urls.py
from django.urls import path

from . import views
from .views import shop_views, chat_views

app_name = 'chat'

urlpatterns=[

    #점포 리스트
    path('shop-list', shop_views.ShopView.as_view(), name='shop-list'),
    #채팅 화면
    path('chat-page', chat_views.ChatView.as_view(), name='chat-page'),
    #해당 점포의 상품 리스트
    path('product-list', chat_views.ProductListView.as_view(), name='product-list'),

]

config/urls.py
from django.contrib import admin
from django.urls import path, include 
from django.conf.urls.static import static
from config import settings
from config.views import index, LoginView, RegisterView, CheckSameId, CheckSameEmail, ChangeMemView, confirmInfo
from django.contrib.auth.views import LogoutView
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index.as_view(), name='index'),

    path('login', LoginView.as_view(), name='login'),
    path('logout',LogoutView.as_view(next_page='./'), name='logout'),
    path('register', RegisterView.as_view(), name='register'),
    path('check-same-id', CheckSameId.as_view(), name='check-same-id'),
    path('check-same-email', CheckSameEmail.as_view(), name='check-same-email'),
    path('confirm-info',confirmInfo.as_view(), name='confirm-info'),
    path('change_mem_info',ChangeMemView.as_view(), name='change_mem_info'),

    path('chat/', include('chat.urls')),
    path('mypage/', include('mypage.urls')),
    path('product/', include('product.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_URL)

mypage/urls.py
from django.urls import path

from .views import checkout_view, review_views, cart_views, like_views, qna_views,\
                    address_views, product_qna_views

app_name = 'mypage'

urlpatterns=[
    path('review', review_views.ReviewView.as_view(), name='review'),
    #path('review-table', review_views.ReviewTableView.as_view(), name='review-table'),
    path('review-post/<str:id>', review_views.ReviewPostView.as_view(), name='review-post'),
    #path('review-detail/<str:id>', review_views.ReviewDetailView.as_view(), name='review-detail'),

    # 마이페이지
    path('cart', cart_views.CartView.as_view(), name='cart'),
    path('checkout', checkout_view.CheckoutView.as_view(), name='checkout'),
    path('checkout-address', checkout_view.AddressView.as_view(), name='checkout-address'),
    path('checkout-coupon', checkout_view.CouponView.as_view(), name='checkout-coupon'),
    path('checkout-confirm', checkout_view.CheckoutConfirmView.as_view(), name='checkout-confirm'),

    path('like', like_views.LikeView.as_view(), name='like'),

    path('address', address_views.AddressView.as_view(), name='address'),
    path('address-modal', address_views.AddressModalView.as_view(), name='address-modal'),

    path('order-history', checkout_view.OrderHistoryView.as_view(), name='order-history'),
    path('order-detail/<str:id>', checkout_view.OrderDetailView.as_view(), name='order-detail'),

    path('qna', qna_views.QnaView.as_view(), name='qna'),
    path('qna-list', qna_views.QnaListView.as_view(), name='qna-list'),
    path('qna-table', qna_views.QnaTableView.as_view(), name='qna-table'),
    path('qna-detail/<str:id>', qna_views.QnaDetailView.as_view(), name='qna-detail'),

    path('product_qna-list', product_qna_views.ProductQnaListView.as_view(), name='product_qna-list'),
    path('product_qna-table', product_qna_views.ProductQnaTableView.as_view(), name='product__qna-table'),
    path('product_qna-detail/<str:id>', product_qna_views.ProductQnaDetailView.as_view(), name='product_qna-detail'),

]

product/urls.py
from django.urls import path
from . import views
from .views import product_views, qna_views,product_best_views, product_search_views

app_name = 'product'

urlpatterns=[
    # path('test', test.TestView.as_view(test)),
    path('qna-post', qna_views.QnaPostView.as_view(), name='qna-post'),
    path('qna-table', qna_views.QnaTableView.as_view(), name='qna-table'),

    path('product-detail/<str:id>', product_views.ProductDetailView.as_view(), name='product-detail'),
    path('product-best', product_best_views.ProductBestView.as_view(), name='product-best'),
    path('product-list/<int:category>', product_views.ProductListView.as_view(), name='product-list'),
    path('product-grid', product_views.ProductGridView.as_view(), name='product-grid'),

    path('search', product_search_views.ProductSearchView.as_view(), name='search'),
    path('search-products', product_search_views.ProductsView.as_view(), name='search-products'),

]

templates/includes/header.html
{% load static %}
{% block stylesheets %}
<link href="{% static 'assets/css/header.css' %}" rel="stylesheet" type="text/css">
<link href="{% static 'assets/css/product.css' %}" rel="stylesheet" type="text/css">

{% endblock stylesheets %}

<header id="header" class="d-flex align-items-center">
  <div class="container header d-flex align-items-center">

    <h1 class="logo me-auto"><a href="{% url 'index' %}">ABCDE</a></h1>
    <!-- Uncomment below if you prefer to use an image logo -->
    <!-- <a href="index.html" class="logo me-auto"><img src="assets/img/logo.png" alt="" class="img-fluid"></a>-->

    <nav id="navbar" class="navbar" id="navbar-header">
      <ul>
        <li class="dropdown"><a href="#"><span>카테고리</span><i class="bi bi-list p-1"></i></a>
          <ul>
            <li class="dropdown"><a href="#"><span>채소</span> <i class="bi bi-chevron-right"></i></a>
              <ul>
                <li><a href="{% url 'product:product-list' 1 %}">친환경</a></li>
                <li><a href="{% url 'product:product-list' 23 %}">고구마/감자/당근</a></li>
                <li><a href="{% url 'product:product-list' 4 %}">시금치/쌈채소/나물</a></li>
                <li><a href="{% url 'product:product-list' 24 %}">브로콜리/파프리카/양배추</a></li>
                <li><a href="{% url 'product:product-list' 25 %}">양파/대파/마늘/배추</a></li>
                <li><a href="{% url 'product:product-list' 26 %}">오이/호박/고추</a></li>
                <li><a href="{% url 'product:product-list' 27 %}">냉동/이색/간편채소</a></li>
                <li><a href="{% url 'product:product-list' 28 %}">콩나물/버섯</a></li>

              </ul>
            </li>
            <li class="dropdown"><a href="#"><span>과일/견과/쌀</span> <i class="bi bi-chevron-right"></i></a>
              <ul>
                <li><a href="{% url 'product:product-list' 29 %}">제철과일</a></li>
                <li><a href="{% url 'product:product-list' 5 %}">국산과일</a></li>
                <li><a href="{% url 'product:product-list' 6 %}">수입과일</a></li>
                <li><a href="{% url 'product:product-list' 7 %}">냉동/건과일</a></li>
                <li><a href="{% url 'product:product-list' 3 %}">견과류</a></li>
                <li><a href="{% url 'product:product-list' 2 %}">쌀/잡곡/혼합곡</a></li>
              </ul>
            </li>
            <li class="dropdown"><a href="#"><span>수산/해산/건어물</span> <i class="bi bi-chevron-right"></i></a>
              <ul>
                <li><a href="{% url 'product:product-list' 30 %}">제철수산</a></li>
                <li><a href="{% url 'product:product-list' 15 %}">생선류</a></li>
                <li><a href="{% url 'product:product-list' 20 %}">수산가공식품</a></li>
                <li><a href="{% url 'product:product-list' 16 %}">해산물</a></li>
                <li><a href="{% url 'product:product-list' 17 %}">어패류</a></li>
                <li><a href="{% url 'product:product-list' 18 %}">건어물</a></li>
                <li><a href="{% url 'product:product-list' 19 %}">김/미역/해조류</a></li>
              </ul>
            </li>
            <li class="dropdown"><a href="#"><span>정육/계란</span> <i class="bi bi-chevron-right"></i></a>
              <ul>
                <li><a href="{% url 'product:product-list' 10 %}">돼지고기</a></li>
                <li><a href="{% url 'product:product-list' 8 %}">소고기</a></li>
                <li><a href="{% url 'product:product-list' 11 %}">닭/오리고기/양고기</a></li>
                <li><a href="{% url 'product:product-list' 12 %}">양념육/돈까스</a></li>
                <li><a href="{% url 'product:product-list' 14 %}">계란류</a></li>
              </ul>
            </li>
            <li class="dropdown"><a href="#"><span>국/반찬/메인요리</span> <i class="bi bi-chevron-right"></i></a>
              <ul>
                <li><a href="{% url 'product:product-list' 31 %}">국/탕/찌개</a></li>
                <li><a href="{% url 'product:product-list' 32 %}">밀키트/메인요리</a></li>
                <li><a href="{% url 'product:product-list' 33 %}">밑반찬</a></li>
                <li><a href="{% url 'product:product-list' 21 %}">김치/젓갈/장류</a></li>
                <li><a href="{% url 'product:product-list' 35 %}">두부/어묵/부침개</a></li>
                <li><a href="{% url 'product:product-list' 36 %}">베이컨/햄/통조림</a></li>
              </ul>
            </li>
            <li class="dropdown"><a href="#"><span>샐러드/간편식</span> <i class="bi bi-chevron-right"></i></a>
              <ul>
                <li><a href="{% url 'product:product-list' 44 %}">샐러드/닭가슴살</a></li>
                <li><a href="{% url 'product:product-list' 45 %}">도시락/밥류</a></li>
                <li><a href="{% url 'product:product-list' 37 %}">파스타/면류</a></li>
                <li><a href="{% url 'product:product-list' 46 %}">떡볶이/튀김/순대</a></li>
                <li><a href="{% url 'product:product-list' 47 %}">피자/핫도그/만두</a></li>
                <li><a href="{% url 'product:product-list' 48 %}">폭립/떡갈비/안주</a></li>
                <li><a href="{% url 'product:product-list' 49 %}">죽/스프/카레/시리얼</a></li>
              </ul>
            </li>
            <li class="dropdown"><a href="#"><span>면/양념/오일</span> <i class="bi bi-chevron-right"></i></a>
              <ul>
                <li><a href="{% url 'product:product-list' 37 %}">파스타/면류</a></li>
                <li><a href="{% url 'product:product-list' 38 %}">식초/소스/드레싱</a></li>
                <li><a href="{% url 'product:product-list' 39 %}">양념/액젓/장류</a></li>
                <li><a href="{% url 'product:product-list' 40 %}">식용유/참기름/오일</a></li>
                <li><a href="{% url 'product:product-list' 41 %}">소금/설탕/향신료</a></li>
                <li><a href="{% url 'product:product-list' 42 %}">밀가루/가루/믹스</a></li>
              </ul>
            </li>
            <li class="dropdown"><a href="#"><span>생수/음료/우유/커피</span> <i class="bi bi-chevron-right"></i></a>
              <ul>
                <li><a href="{% url 'product:product-list' 43 %}">생수/탄산수</a></li>
                <li><a href="{% url 'product:product-list' 51 %}">음료/주스</a></li>
                <li><a href="{% url 'product:product-list' 52 %}">우유/두유/요거트</a></li>
                <li><a href="{% url 'product:product-list' 53 %}">커피/차</a></li>
              </ul>
            </li>
            <li class="dropdown"><a href="#"><span>간식/과자/떡</span> <i class="bi bi-chevron-right"></i></a>
              <ul>
                <li><a href="{% url 'product:product-list' 54 %}">과자/쿠키</a></li>
                <li><a href="{% url 'product:product-list' 55 %}">초콜릿/젤리/캔디</a></li>
                <li><a href="{% url 'product:product-list' 56 %}">떡/한과</a></li>
                <li><a href="{% url 'product:product-list' 57 %}">아이스크림</a></li>
              </ul>
            </li>
            <li class="dropdown"><a href="#"><span>베이커리/치즈/델리</span> <i class="bi bi-chevron-right"></i></a>
              <ul>
                <li><a href="{% url 'product:product-list' 58 %}">식빵/빵류/</a></li>
                <li><a href="{% url 'product:product-list' 59 %}">잼/버터/스프레드</a></li>
                <li><a href="{% url 'product:product-list' 60 %}">케이크/파이/디저트</a></li>
                <li><a href="{% url 'product:product-list' 61 %}">치즈</a></li>
              </ul>
            </li>
            <li class="dropdown"><a href="#"><span>건강식품</span> <i class="bi bi-chevron-right"></i></a>
              <ul>
                <li><a href="{% url 'product:product-list' 62 %}">영양제</a></li>
                <li><a href="{% url 'product:product-list' 63 %}">홍삼/인삼/꿀</a></li>
                <li><a href="{% url 'product:product-list' 64 %}">건강즙/건강음료/건강환</a></li>
              </ul>
            </li>
            <li class="dropdown"><a href="#"><span>주류</span> <i class="bi bi-chevron-right"></i></a>
              <ul>
                <li><a href="{% url 'product:product-list' 65 %}">와인/샴페인</a></li>
                <li><a href="{% url 'product:product-list' 68 %}">증류주/과일주</a></li>
                <li><a href="{% url 'product:product-list' 69 %}">막걸리/약주</a></li>
              </ul>
            </li>
          </ul>
        </li>
        <li><a class="nav-link scrollto" href="{% url 'product:product-best' %}">베스트</a></li>
        <li><a href="{% url 'chat:shop-list' %}">점포 구경하기</a></li>
        <li><a class="nav-link scrollto" href="#">행사 둘러보기</a></li>
        <!--
        <li><a class="getstarted scrollto" href="#about">Get Started</a></li>
        -->
      </ul>

      <div class="search" id="search">
        <form
          novalidate=""
          method="post"
          action="{% url 'product:search' %}"
          enctype="multipart/form-data"
        >
        {% csrf_token %}
          <div class="search__column">
            <input class="search__keyword" type="text" name="keyword" placeholder="검색어를 입력하세요"/>
            <button class="nav-link scrollto search__button"  type="submit">
              <i class="bi bi-search"></i>
            </button>
          </div>
      </form>
        <a href="{% url 'mypage:address' %}"><i class="bi bi-geo-alt"></i></a>
        <a class="nav-link scrollto nav-cart" href="{% url 'mypage:cart' %}">
          <i class="bi bi-cart2">
            {% if request.user.id %}
            <span class="cart-notification">{{ cart }}</span>
            {% endif %}
          </i>
        </a>
        {% if request.user.id %}
        <li class="dropdown">
          <a class="nav-link scrollto" href="#"><i class="bi bi-person" style="align-items: center;"></i></a>
          <ul>
            <li><a class="nav-link" href="#">마이페이지</a></li>
            <li><a class="nav-link" href="{% url 'mypage:order-history' %}">주문내역</a></li>
            <li><a class="nav-link" href="{% url 'mypage:like' %}">찜한 목록</a></li>
            <li><a class="nav-link" href="{% url 'confirm-info' %}">회원정보수정</a></li>
            <li><a class="nav-link" href="{% url 'logout' %}">로그아웃</a></li>
          </ul>
        </li>
        {% else %}
        <li class="dropdown">
          <a class="nav-link scrollto active" href="#"><i class="bi bi-person" style="align-items: center;"></i></a>
          <ul>
            <li><a class="nav-link" href="{% url 'login' %}">로그인</a></li>
            <li><a class="nav-link" href="{% url 'register' %}">회원가입</a></li>
          </ul>
        </li>
        {% endif %}
      </div>

      <i class="bi bi-list mobile-nav-toggle"></i>
    </nav>
    <!-- .navbar -->
    <nav class="nav" id="nav-mobile">
      <ul class="nav__list">
        <li class="nav__btn">
          <a class="nav__link" href="#"><i class="bi bi-house-door"></i></a>
        </li>
        <li class="nav__btn">
          <a class="nav__link" href="#"><i class="bi bi-search"></i></a>
        </li>
        <li class="nav__btn">
          <a class="nav__link" href="#"><i class="bi bi-list"></i></a>
        </li>
        <li class="nav__btn">
          <a class="nav__link" href="#"><i class="bi bi-person"></i></a>
        </li>
      </ul>
    </nav>
  </div>
</header>
<!-- End Header -->
<script src="https://code.jquery.com/jquery-3.6.0.js"></script>

<script src="{% static 'jsmeta/header.js' %}"></script>
<script src="{% static 'jsmeta/product/script_product-search.js' %}"></script>

templates/includes/navigation.html
  <section id="topbar" class="d-flex align-items-center">
    <div class="container d-flex justify-content-center justify-content-md-between">
      <div class="contact-info d-flex align-items-center">
        <i class="bi bi-envelope-fill"></i><a href="mailto:contact@example.com">info@example.com</a>
        <i class="bi bi-phone-fill phone-icon"></i> +1 5589 55488 55
      </div>
      <div class="social-links d-none d-md-block">
        <a href="#" class="twitter"><i class="bi bi-twitter"></i></a>
        <a href="#" class="facebook"><i class="bi bi-facebook"></i></a>
        <a href="#" class="instagram"><i class="bi bi-instagram"></i></a>
        <a href="#" class="linkedin"><i class="bi bi-linkedin"></i></i></a>
        <a href="#">
          {% if memname %}
            {{memname}} 님
          {% endif %}
        </a>
      </div>
    </div>
  </section>

templates/includes/scripts.html
{% load static %}
<script src="https://code.jquery.com/jquery-3.6.0.js"></script>
<script src="https://code.jquery.com/ui/1.13.0/jquery-ui.js"></script>

{% comment %} 
<script src="{% static 'assets/vendor/jquery/jquery.min.js' %}"></script> {% endcomment %}
<script src="{% static 'assets/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
<script src="{% static 'assets/vendor/jquery-easing/jquery.easing.min.js' %}"></script>
<script
  src="https://kit.fontawesome.com/6478f529f2.js"
  crossorigin="anonymous"
></script>
    
<script  type="text/javascript">
// https://docs.djangoproject.com/en/3.1/ref/csrf/
function getCookie(name) {
  let cookieValue = null;
  if (document.cookie && document.cookie !== '') {
      const cookies = document.cookie.split(';');
      for (let i = 0; i < cookies.length; i++) {
          const cookie = cookies[i].trim();
          // Does this cookie string begin with the name we want?
          if (cookie.substring(0, name.length + 1) === (name + '=')) {
              cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
              break;
          }
      }
  }
  return cookieValue;
}
var csrftoken = getCookie('csrftoken');

var xhr; 


</script>