chat/urls.py
from django.urls import path

from . import views
from .views import shop_views, chat_views

app_name = 'chat'

urlpatterns=[

    #점포 리스트
    path('shop-list', shop_views.ShopView.as_view(), name='shop-list'),
    #채팅 화면
    path('chat-page', chat_views.ChatView.as_view(), name='chat-page'),
    #해당 점포의 상품 리스트
    path('product-list', chat_views.ProductListView.as_view(), name='product-list'),

]

config/urls.py
from django.contrib import admin
from django.urls import path, include 
from django.conf.urls.static import static
from config import settings
from config.views import index, LoginView, RegisterView, CheckSameId, CheckSameEmail, ChangeMemView, confirmInfo
from django.contrib.auth.views import LogoutView
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index.as_view(), name='index'),

    path('login', LoginView.as_view(), name='login'),
    path('logout',LogoutView.as_view(next_page='./'), name='logout'),
    path('register', RegisterView.as_view(), name='register'),
    path('check-same-id', CheckSameId.as_view(), name='check-same-id'),
    path('check-same-email', CheckSameEmail.as_view(), name='check-same-email'),
    path('confirm-info',confirmInfo.as_view(), name='confirm-info'),
    path('change_mem_info',ChangeMemView.as_view(), name='change_mem_info'),

    path('chat/', include('chat.urls')),
    path('mypage/', include('mypage.urls')),
    path('product/', include('product.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_URL)

mypage/urls.py
from django.urls import path

from .views import checkout_view, review_views, cart_views, like_views, qna_views,\
                    address_views, product_qna_views

app_name = 'mypage'

urlpatterns=[
    path('review', review_views.ReviewView.as_view(), name='review'),
    #path('review-table', review_views.ReviewTableView.as_view(), name='review-table'),
    path('review-post/<str:id>', review_views.ReviewPostView.as_view(), name='review-post'),
    #path('review-detail/<str:id>', review_views.ReviewDetailView.as_view(), name='review-detail'),

    # 마이페이지
    path('cart', cart_views.CartView.as_view(), name='cart'),
    path('checkout', checkout_view.CheckoutView.as_view(), name='checkout'),
    path('checkout-address', checkout_view.AddressView.as_view(), name='checkout-address'),
    path('checkout-coupon', checkout_view.CouponView.as_view(), name='checkout-coupon'),
    path('checkout-confirm', checkout_view.CheckoutConfirmView.as_view(), name='checkout-confirm'),

    path('like', like_views.LikeView.as_view(), name='like'),

    path('address', address_views.AddressView.as_view(), name='address'),
    path('address-modal', address_views.AddressModalView.as_view(), name='address-modal'),

    path('order-history', checkout_view.OrderHistoryView.as_view(), name='order-history'),
    path('order-detail/<str:id>', checkout_view.OrderDetailView.as_view(), name='order-detail'),

    path('qna', qna_views.QnaView.as_view(), name='qna'),
    path('qna-list', qna_views.QnaListView.as_view(), name='qna-list'),
    path('qna-table', qna_views.QnaTableView.as_view(), name='qna-table'),
    path('qna-detail/<str:id>', qna_views.QnaDetailView.as_view(), name='qna-detail'),

    path('product_qna-list', product_qna_views.ProductQnaListView.as_view(), name='product_qna-list'),
    path('product_qna-table', product_qna_views.ProductQnaTableView.as_view(), name='product__qna-table'),
    path('product_qna-detail/<str:id>', product_qna_views.ProductQnaDetailView.as_view(), name='product_qna-detail'),

]

mypage/models.py
from django.db import models

# Create your models here.

mypage/views/address_views.py
import json
from django.http import HttpRequest, JsonResponse 
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic.base import View
from django.contrib.auth.mixins import LoginRequiredMixin
from datetime import datetime

from config.models import Address, Member, CartProduct

class AddressView(LoginRequiredMixin, View):
    '''
    배송지 관리
    '''
    def get(self, request: HttpRequest):
        context={}
        context['addresses']=list(Address.objects.filter(deleteflag='0', member__user=request.user).order_by('-created_at')\
                                  .values('ad_name', 'code', 'ad_detail', 'id'))
        context['memname'] = list(Member.objects.filter(user_id=request.user.id).values_list('mem_name', flat=True))[0]
        context['cart'] = CartProduct.objects.filter(cart__member__user=request.user, deleteflag='0').count()
        
        return render(request, 'address.html', context)

    def post(self, request:HttpRequest):
        context={}
        request.POST=json.loads(request.body)

        code=request.POST.get('code')
        ad_detail=request.POST.get('ad_detail')
        #name=request.POST.get('name')
        #call=request.POST.get('call')

        Address.objects.create(
            deleteflag='0',
            code=code,
            ad_detail=ad_detail,
            #name=name,
            #call=call,
            member=Member.objects.get(user=request.user),
        )

        context['success']=True

        return JsonResponse(context, content_type='application/json')

    def put(self, request:HttpRequest):
        context={}
        request.PUT=json.loads(request.body)

        id=request.PUT.get('id')
        ad_name=request.PUT.get('ad_name')
        name=request.PUT.get('name')
        call=request.PUT.get('call')

        Address.objects.filter(id=id).update(
            ad_name=ad_name,
            name=name,
            call=call,
            updated_at=datetime.now(),
        )
      
        context['success']=True

        return JsonResponse(context, content_type='application/json')
    
    def delete(self, request:HttpRequest):
        context={}
        request.DELETE=json.loads(request.body)

        id=request.DELETE.get('id')

        Address.objects.filter(id=id).update(
            deleteflag='1',
            deleted_at=datetime.now(),
        )
      
        context['success']=True

        return JsonResponse(context, content_type='application/json')


class AddressModalView(LoginRequiredMixin, View):
    '''
    배송지 관리

    배송지 수정 모달에 들어갈 정보를 받아옵니다
    '''
    def get(self, request: HttpRequest):
        context={}
        id=request.GET.get('id')

        context['address']=list(Address.objects.filter(id=id).values('id', 'ad_detail', 'ad_name', 'call', 'name', 'road_ad'))[0]
        context['success']=True

        return JsonResponse(context, content_type='application/json')

mypage/views/cart_views.py
import json
from django.forms import FloatField, IntegerField
from django.http import HttpRequest, JsonResponse 
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic.base import View
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import F
from django.db.models import IntegerField
from django.db.models.functions import Cast
from datetime import datetime

from config.models import Product, CartProduct, Cart, Member
from product.views.product_views import doesCartExist


class CartView(LoginRequiredMixin, View):
    '''
    장바구니
    '''

    def get(self, request: HttpRequest, *args, **kwargs):
        context={}
        products=[]
        main_imgs=[]
        total_price=0

        if(doesCartExist is False):
            return render(request, 'cart.html',  context)

        cart=list(Cart.objects.filter(member__user_id=request.user.id).values_list('id', flat=True))[0]
        products_in_cart=list(CartProduct.objects.filter(cart=cart, deleteflag='0').order_by('-updated_at').values_list('product', flat=True))

        for p in products_in_cart:
            products.extend(CartProduct.objects.filter(product=p, cart=cart, deleteflag='0').order_by('-updated_at').values('product__main_img', 'product__name', \
                'product__price', 'amount', 'product__id', 'cart__id').annotate(total=Cast(F('amount') * F('product__price'), IntegerField())))
            main_imgs.append(Product.objects.get(id=p))

        for p in products:
            total_price=total_price+p.get('total')

        #context['products']=zip(products, main_imgs)
        context['main_imgs']=main_imgs
        context['products']=products
        context['total_price']=total_price
        context['memname'] = list(Member.objects.filter(user_id=request.user.id).values_list('mem_name', flat=True))[0]
        context['cart'] = CartProduct.objects.filter(cart__member__user=request.user, deleteflag='0').count()

        return render(request, 'cart.html',  context)
    
    def delete(self, request: HttpRequest, *args, **kwargs):
        context={}
        request.DELETE = json.loads(request.body)

        product_id = request.DELETE.get('product_id')
        cart_id = request.GET.get('cart_id')

        CartProduct.objects.filter(cart=cart_id, product=product_id).update(
            amount=0,
            deleteflag='1',
            deleted_at=datetime.now(),
        )
        context['success']=True

        return JsonResponse(context, content_type='application/json')

    def put(self, request: HttpRequest, *args, **kwargs):
        context={}
        request.PUT = json.loads(request.body)

        cart_id=list(Cart.objects.filter(member__user_id=request.user.id).values_list('id', flat=True))[0]
        product_id = request.PUT.get('product_id')
        amount = request.PUT.get('amount')

        CartProduct.objects.filter(cart=cart_id, product=product_id).update(
            amount=amount,
        )
        context['success']=True

        return JsonResponse(context, content_type='application/json')

mypage/views/like_views.py
import json
from django.http import HttpRequest, JsonResponse 
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic.base import View
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models.functions import Cast
from datetime import datetime
from config.models import Product, Liked, LikedProduct, Member, CartProduct


class LikeView(LoginRequiredMixin, View):
    '''
    찜한상품
    '''
    def get(self, request: HttpRequest, *args, **kwargs):
        context={}
        user_id=request.user.id
        liked_products=[]

        if(doesListExist(user_id) is False):
            return render(request, 'like.html', context)
        
        products=list(LikedProduct.objects.filter(liked__member__user_id=user_id, deleteflag='0').order_by('-updated_at').values_list('product__id', flat=True))
        for product in products:
            liked_products.append(Product.objects.get(id=product))
        
        context={
          'liked_products': liked_products,
          'memname': list(Member.objects.filter(user_id=request.user.id).values_list('mem_name', flat=True))[0],
          'cart': CartProduct.objects.filter(cart__member__user=request.user, deleteflag='0').count(),
          'memname': list(Member.objects.filter(user_id=request.user.id).values_list('mem_name', flat=True))[0],
          'cart': CartProduct.objects.filter(cart__member__user=request.user, deleteflag='0').count()
        }

        return render(request, 'like.html', context)
    
    def put(self, request: HttpRequest, *args, **kwargs):
        context={}
        request.PUT = json.loads(request.body)

        id = request.PUT.get('id')
        isLiked = request.PUT.get('isLiked')
        user_id=request.user.id

        # Create a Liked if cart does not exist
        if(doesListExist(user_id) is False):
            Liked.objects.create(
                member=Member.objects.filter(user_id=user_id).first(),
                deleteflag='0',
            )

        # Add product to wish list
        list_id=list(Liked.objects.filter(member__user_id=user_id).values_list('id', flat=True))[0]
        
        # LikedProduct에 존재하지 않는다면
        if(existsInList(list_id, id) is False):
            LikedProduct.objects.create(
                product=Product.objects.filter(id=id).first(),
                liked=Liked.objects.filter(id=list_id).first(),
                deleteflag='0',
            )
        else:
            liked_product_id=list(LikedProduct.objects.filter(liked_id__member_id__user_id=user_id, product_id=id).values_list('id', flat=True))[0]

            # LikedProduct에 존재 & 찜한 상태
            if(isLiked is True):
                LikedProduct.objects.filter(id=(liked_product_id)).update(
                    deleteflag='1',
                    updated_at=datetime.now(),
                )
            # LikedProduct에 존재 & 찜x
            else:
                LikedProduct.objects.filter(id=(liked_product_id)).update(
                    deleteflag='0',
                    updated_at=datetime.now(),
                )

        context['success']=True

        return JsonResponse(context, content_type='application/json')
    
    def delete(self, request:HttpRequest, *args, **kwargs):
        context={}
        request.PUT = json.loads(request.body)

        product_id = request.PUT.get('product_id')
        liked_id = list(Liked.objects.filter(member__user_id=request.user.id).values_list('id'))[0]

        LikedProduct.objects.filter(liked=liked_id, product=product_id).update(
            deleteflag='1',
            updated_at=datetime.now(),
        )
        context['success']=True

        return JsonResponse(context, content_type='application/json')

def doesListExist(id):
    if (Liked.objects.filter(member__user_id=id).count() > 0):
        return True
    return False

def isAlreadyInList(liked_id, product_id):
    if(LikedProduct.objects.filter(liked__id=liked_id, product=product_id, deleteflag='0').exists()):
        return True
    return False

def existsInList(liked_id, product_id):
    if(LikedProduct.objects.filter(liked__id=liked_id, product=product_id).exists()):
        return True
    return False

mypage/views/product_qna_views.py
import json
from django.http import HttpRequest, JsonResponse 
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic.base import View
from django.contrib.auth.mixins import LoginRequiredMixin
from datetime import datetime

from config.models import ProQna, ProQnaAnswer, Member, CartProduct

class ProductQnaListView(LoginRequiredMixin, View):
    '''
    1:1 문의 목록
    '''
    template_name = 'product_qna_list.html' 

    def get(self, request: HttpRequest, *args, **kwargs):
        context = {}

        context['memname']=list(Member.objects.filter(user_id=request.user.id).values_list('mem_name', flat=True))[0]
        context['cart']=CartProduct.objects.filter(cart__member__user=request.user, deleteflag='0').count()
        
        return render(request, self.template_name, context)
    
    def delete(self, request:HttpRequest):
        context={}
        request.DELETE = json.loads(request.body)

        qna_id=request.DELETE.get('qna_id')
        
        try:
            ProQna.objects.filter(id=qna_id).update(
                deleteflag='1',
                deleted_at=datetime.now(),
            )
            context['success']=True
        
        except Exception as e:
            context['success']=False

        return JsonResponse(context, content_type='application/json')


class ProductQnaTableView(LoginRequiredMixin, View):
    '''
    1:1 문의 목록

    DataTable에 넣을 문의 목록을 받아옵니다.
    '''
    def get(self, request: HttpRequest, *args, **kwargs):
        context={}
        context['qna']=list(ProQna.objects.filter(deleteflag='0', member__user=request.user).order_by('-created_at')\
                                        .values('created_at', 'answer_flag', 'title', 'id', 'product__name'))

        return JsonResponse(context, content_type='application/json')


class ProductQnaDetailView(LoginRequiredMixin, View):
    '''
    상품 문의 상세 페이지
    '''

    def get(self, request: HttpRequest, *args, **kwargs):
        id = kwargs.get('id')
        context={}
        context['memname']=list(Member.objects.filter(user_id=request.user.id).values_list('mem_name', flat=True))[0]
        context['cart']=CartProduct.objects.filter(cart__member__user=request.user, deleteflag='0').count()

        context['qna'] = list(ProQna.objects.filter(id=id).values('title', 'content', 'created_at', 'answer_flag', 'id'))[0]

        # 문의 답변이 등록되어 있다면 
        if context['qna'].get('answer_flag')=='1':
            context['answer']=ProQnaAnswer.objects.get(qna__id=id)
        
        return render(request, 'product_qna_detail.html', context)

mypage/templates/address.html
{% extends 'layouts/base.html' %}
{% load static %}

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}
<link href="{% static 'assets/css/product.css' %}" rel="stylesheet" type="text/css">
{% endblock stylesheets %}

{% block content %}
<div class="container mt-5">
  <div class="row pt-3">
    <aside class="col-lg-3">
      <!--  COMPONENT MENU LIST  -->
      <div class="card p-3 h-100">
        <nav class="nav flex-column nav-pills">
          <a class="nav-link" href="{% url 'mypage:order-history' %}">주문내역</a>
          <a class="nav-link" href="{% url 'mypage:like' %}">찜한 목록</a>
          <a class="nav-link active" href="{% url 'mypage:address' %}">배송지 관리</a>
          <a class="nav-link" href="#">결제수단 관리</a>
          <a class="nav-link" href="{% url 'mypage:review' %}">상품 후기</a>
          <a class="nav-link" href="{% url 'mypage:product_qna-list' %}">상품 문의</a>
          <a class="nav-link" href="{% url 'mypage:qna-list' %}">1:1 문의</a>
          <a class="nav-link" href="{% url 'confirm-info' %}">회원정보 수정</a>
          <a class="nav-link" href="{% url 'logout' %}">로그아웃</a>
        </nav>
      </div>
      <!--   COMPONENT MENU LIST END .//   -->
    </aside>
    <main class="col-lg-9">
      <article class="card mb-5 pb-5">
      <div class="card-body">
        <h4 class="card-title mb-4">배송지 관리</h4>
        <p class="text-muted">배송지 목록</p>
        <div class="row g-2 mb-3" id="address-table">
          {% if addresses %}
          {% for address in addresses %}
          <div class="col-md-12">
            <article class="box col-md-12">
              <b class="mx-2 text-muted"><i class="fa fa-map-marker-alt"></i></b> 
              <span class="col-md-9" onclick="openModal(this);" style="cursor:pointer;" value="{{address.id}}">{{address.ad_detail}}</span>
            </article>
          </div> <!-- col.// -->
          {% endfor %}
          {% endif %}
        </div> <!-- row.// -->
        <button id="address-button" class="btn btn-primary" data-toggle="modal" data-target="#address-modal">
          <i class="me-2 fa fa-plus"></i>새로운 배송지 추가
        </button>
      </div> <!-- card-body .// -->
      </article> <!-- card .// --> 
    </main>
    </div> <!-- row.// -->
</div>

<!--배송지 추가 모달-->
<div class="modal fade" id="address-add" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabelLogout">배송지 추가</h5>
        <button type="button" class="close" data-dismiss="modal" id="modal-close" onclick="closeModalToAdd();">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <div class="row justify-content-center my-4">
          <div class="col-lg-10">
            <div class="form-group row mb-4">
              <div class="col-md-9 p-0">
                <input class="form-control" type="text" autocomplete="on" id="address" name='address' readonly/>
              </div>
              <div class="col-md-3">
                <button class="btn btn-outline-primary" type="button" id="address-relookup">재검색</button>
              </div>
            </div>
            <div class="form-group row mb-4">
              <input class="form-control" type="text" id="address-detail" name="address-detail" placeholder="나머지 주소를 입력해주세요" required/>
            </div>
          </div>
          <button class="btn btn-primary my-3 col-lg-10" type="submit" onclick="addAddress()">확인</button>
        </div>
      </div>
    </div>
  </div>
</div>

<!--배송지 수정 및 삭제 모달-->
<div class="modal fade" id="address-edit" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabelLogout">배송지 수정</h5>
        <button type="button" class="close" data-dismiss="modal" id="modal-close" onclick="closeModalToEdit();">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <div class="row justify-content-center my-3">
          <div class="col-lg-10">
            <div class="form-group row mb-3">
              <input class="form-control" type="text" id="addressToEdit" name="addressToEdit" readonly/>
            </div>
            <div class="form-group row mb-3">
              <label class="mb-1">배송지 이름</label>
              <input class="form-control" type="text" id="address-name" name="address-name"/>
            </div>
            <div class="form-group row mb-3">
              <label class="mb-1">받으실 분</label>
              <input class="form-control" type="text" autocomplete="on" id="address-member"/>
            </div>
            <div class="form-group row">
              <label class="mb-1">연락처</label>
              <input class="form-control" type="text" autocomplete="on" id="address-call"/>
            </div>
          </div>
        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-outline-primary" data-dismiss="modal" onclick="deleteAddress();">삭제</button>
        <button type="button" class="btn btn-primary" onclick="editAddress();">수정</a>
      </div>
    </div>
  </div>
</div>
{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}
<!--카카오 우편번호 찾기-->
<script src="//t1.daumcdn.net/mapjsapi/bundle/postcode/prod/postcode.v2.js"></script>

<script src="{% static 'jsmeta/mypage/script_address.js' %}"></script>
{% endblock javascripts %}

mypage/templates/like.html
{% extends 'layouts/base.html' %}
{% load static %}

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}
<link href="{% static 'assets/css/product.css' %}" rel="stylesheet" type="text/css">
{% endblock stylesheets %}

{% block content %}
<div class="container mt-5">
  <div class="row pt-3">
    <aside class="col-lg-3">
      <!--  COMPONENT MENU LIST  -->
      <div class="card p-3 h-100">
        <nav class="nav flex-column nav-pills">
          <a class="nav-link" href="{% url 'mypage:order-history' %}">주문내역</a>
          <a class="nav-link active" href="{% url 'mypage:like' %}">찜한 목록</a>
          <a class="nav-link" href="{% url 'mypage:address' %}">배송지 관리</a>
          <a class="nav-link" href="#">결제수단 관리</a>
          <a class="nav-link" href="{% url 'mypage:review' %}">상품 후기</a>
          <a class="nav-link" href="{% url 'mypage:product_qna-list' %}">상품 문의</a>
          <a class="nav-link" href="{% url 'mypage:qna-list' %}">1:1 문의</a>
          <a class="nav-link" href="{% url 'confirm-info' %}">회원정보 수정</a>
          <a class="nav-link" href="{% url 'logout' %}">로그아웃</a>
        </nav>
      </div>
      <!--   COMPONENT MENU LIST END .//   -->
    </aside>
    <main class="col-lg-9">
      {% if liked_products %}
      {% load humanize %}
      {% load index %}
      <div class="card">
        <div class="content-body">
          <h4 class="card-title mb-4">찜한 목록</h4>
          <div id="like-table">
            {% for p in liked_products %}
            <article class="row gy-3 my-2">
              <div class="col-lg-8">
                <figure class="itemside me-lg-5">
                  <div class="aside">
                    <img src="{{ p.main_img.url }}" 
                        class="img-md border rounded" 
                        onclick="window.open('/product/product-detail/'+'{{ p.id }}'+'','_self');"
                        style="cursor:pointer;">
                  </div>
                  <figcaption class="info pt-1">
                    <h6 class="title mb-2"
                      onclick="window.open('/product/product-detail/'+'{{ p.id }}'+'','_self');"
                      style="cursor:pointer;">{{p.name}}</h6>
                    <p class="text-muted"> 옵션: Yellow, Jeans </p>
                  </figcaption>
                </figure>
              </div>
              <div class="col-lg-2 col-sm-4 col-6">
                <div class="price-wrap lh-sm pt-2"> 
                  <var class="price h6">{{p.price | intcomma}}원</var>  <br>
                </div> <!-- price-wrap .// -->
              </div>
              <div class="col-lg col-sm-4">
                <div class="float-lg-end">
                  <a href="#" class="btn btn-light text-danger" value="{{p.id}}" onclick="deleteFromWishlist(this)">
                    <i class="fa fa-trash"></i>
                  </a>
                </div>
              </div>
            </article> <!-- row.// -->
            {% endfor %}
          </div>
        </div> <!-- card-body .// -->
        <div class="content-body border-top">
          <p><i class="me-2 text-muted fa-lg fa fa-truck"></i> Free Delivery within 1-2 weeks</p>
          <p class="text-muted">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
          tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
          quis nostrud exercitation ullamco laboris nisi ut aliquip</p>
        </div> <!-- card-body.// -->
    
      </div> <!-- card.// -->
      {% endif %}
    </main>
  </div> <!-- row.// -->
</div>

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}
<script src="{% static 'jsmeta/mypage/script_like.js' %}"></script>
{% endblock javascripts %}

mypage/templates/product_qna_detail.html
{% extends 'layouts/base.html' %}
{% load static %}

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}
<link href="{% static 'assets/css/product.css' %}" rel="stylesheet" type="text/css">
{% endblock stylesheets %}

{% block content %}
<div class="container mt-5">
  <div class="row pt-3">
    <aside class="col-lg-3">
      <!--  COMPONENT MENU LIST  -->
      <div class="card p-3 h-100">
        <nav class="nav flex-column nav-pills">
          <a class="nav-link" href="{% url 'mypage:order-history' %}">주문내역</a>
          <a class="nav-link" href="{% url 'mypage:like' %}">찜한 목록</a>
          <a class="nav-link" href="{% url 'mypage:address' %}">배송지 관리</a>
          <a class="nav-link" href="#">결제수단 관리</a>
          <a class="nav-link" href="{% url 'mypage:review' %}">상품 후기</a>
          <a class="nav-link active" href="{% url 'mypage:product_qna-list' %}">상품 문의</a>
          <a class="nav-link" href="{% url 'mypage:qna-list' %}">1:1 문의</a>
          <a class="nav-link" href="{% url 'confirm-info' %}">회원정보 수정</a>
          <a class="nav-link" href="{% url 'logout' %}">로그아웃</a>
        </nav>
      </div>
      <!--   COMPONENT MENU LIST END .//   -->
    </aside>
    <main class="col-lg-9">
      <div class="card mb-5">
        <div class="card-body">
          <h4 class="card-title mb-4">상품 문의</h4>
          <hr>
          <blockquote>
            {% if qna.answer_flag == '0' %}
            <div class="dropdown float-lg-end d-flex mb-3">
              <button class="dropbtn btn btn-light btn-sm float-end"> <i class="fa fa-ellipsis-v"></i> </button>
              <div class="dropdown-content">
                <li onclick="deleteQuestion('{{qna.id}}')">삭제</li>
              </div>
            </div>
            {% endif %}
            <div class="icontext">
              <div class="text">
                <h6 class="mb-0"> {{ qna.title }} </h6>
                <div class="rating-wrap">
                  <b class="dot"></b>
                  <small class="label-rating text-muted"> {{ qna.created_at|date:"Y-m-d"}} 에 작성함 </small>
                </div>
              </div>
            </div> <!-- icontext.// -->
            <div class="col mt-3 px-2" id="qna-question">
              <p>{{ qna.content }}</p>
            </div>
            {% if image.qna_img %}
            <div class="gallery-uploader-wrap mb-4 px-2">
              <div id="uploaded_image">
                <label class="uploader-img">
                  <img src="{{image.qna_img.url}}" onclick="window.open(this.src)" style="cursor:pointer;">
                </label>
              </div>
            </div>
            {% endif %}
          </blockquote>
          {% if answer %}
          <blockquote class="border-top my-3 pt-3 px-2">
            <div class="col mt-3" >
              <p>{{ answer.content }}</p>
            </div>
            <small class="label-rating text-muted"> {{ answer.created_at|date:"Y-m-d"}}</small>
          </blockquote>
          {% endif %}
        </div> <!-- card-body end.// -->
      </div> <!-- card end.// -->
    </main>
  </div> <!-- row.// -->
</div>

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}
<script src="{% static 'jsmeta/mypage/script_product_qna_detail.js' %}"></script>
{% endblock javascripts %}